CREATE TABLE IF NOT EXISTS products (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    active boolean NOT NULL
);

-- Insert products data
INSERT INTO products (name, price, active)
VALUES ('Telefono', 5000, true);

INSERT INTO products (name, price, active)
VALUES ('Cargador', 4000, true);

INSERT INTO products (name, price, active)
VALUES ('Audifonos', 2000, true);

INSERT INTO products (name, price, active)
VALUES ('Forro', 3000, true);